### PR TITLE
Add php 7.4 support 

### PR DESCRIPTION
**Pull request by NurdinDev**
#1

### CODE REVIEW

**Comment by NurdinDev** [comment]
I realized "php:7.4-cli-stretch" not found

**Comment by NurdinDev** [comment]
I add 7.4 support because my local `metasyntactical/composer-plugin-license-check` with version 0.5 not working so I've updated to 0.6, and to pass gitlab ci I need to pull up the PHP 7.4 in my docker container.

**Comment by jankarres** [comment]
Thanks for your PR. @matzeeable, who is responsible for this repository at devowl.io, will be back from vacation in a week, and he will look at your PR.

**Comment by matzeeable** [comment]
Hi @NurdinDev ! Please checkout #1 .

**Pull request closed without merging**
